include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    [
      lib/**.g.dart,
      lib/configs/di/injection.config.dart,
      integration_test/gherkin_suite_test_develop.g.dart,
      integration_test/gherkin_suite_test_staging.g.dart,
      integration_test/gherkin_suite_test_production.g.dart,
    ]

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
